### ISSUE TITLE
Version 1.0.2 is not accessible via CocoaPods

### ISSUE THREAD

**Issue by erikackermann** [dropbox/zxcvbn-ios#14]
I think 1.0.2 needs to be published still.  Not seeing it here:
https://github.com/CocoaPods/Specs/tree/master/Specs/zxcvbn-ios

`pod trunk push`

**Comment by leah** [comment]
Sorry! I needed to update the version since the linter found an error in 1.0.2. So the newest version is 1.0.3. Thanks for your help!

**Comment by erikackermann** [comment]
No problem.  Thanks so much!
