### ISSUE TITLE
Unintuitive import syntax when using as dynamic framework

### ISSUE THREAD

**Issue by erikackermann** [dropbox/zxcvbn-ios#15]
Because of the `-` character in this cocoapod's name, the generated framework is named `zxcvbn_ios`.  The required import to use this pod is then:

```
#import <zxcvbn_ios/DBZxcvbn.h>
```

Would be nice if this were documented somewhere (or if the name matched convention: `<zxcvbn/zxcvbn.h>`).

**Comment by mittenimraum** [comment]
Yes, that would be nice.

**Comment by leah** [comment]
I've updated the README to include the import which now looks like `#import <Zxcvbn/DBZxcvbn.h>`. I'm open to nicer formats, so pull requests welcome!
